name: at_event
description: A new Flutter application.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependency_overrides:
  intl: ^0.17.0


dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.1
  at_onboarding_flutter: ^1.0.0+4
  at_client_mobile: ^1.0.0+4
  at_server_status: ^0.1.0+1
  cupertino_icons: ^0.1.3
  modal_progress_hud: any
  provider: ^5.0.0
  at_demo_data: ^0.0.3+1
  syncfusion_flutter_calendar: ^19.1.67
  toggle_switch: ^1.0.0+1
  adobe_xd: ^2.0.0+1
  table_calendar: ^3.0.0
  date_time_picker: ^2.0.0
  at_contacts_flutter: ^1.0.2
  at_contact: ^1.0.0
  fluttertoast: ^8.0.7
  at_location_flutter: ^1.0.3
  latlng: any
  image_picker: ^0.8.1+3
  http: ^0.13.3
  firebase_core: ^1.3.0
  firebase_storage: ^9.0.0
  cloud_firestore: ^2.3.0
  flutter_spinkit: ^5.0.0




flutter:

  assets:
    - assets/images/


  uses-material-design: true
